SELECT [AbsenceID]
      ,[FromDate]
      ,[ToDate]
      ,[Reason]
      ,[EmployeeID]
      ,[EmployeeNumber]
      ,[CountryID]
      ,[Name]
      ,[Code]
      ,[Firstname]
      ,[Lastname]
      ,[Birthday]
      ,[Street]
      ,[Housenumber]
      ,[Postalcode]
      ,[City]
      ,[Phonenumber]
      ,[Email]
      ,[AbsenceTypeID]
      ,[Label]
  FROM [dbo].[AbsencesWithEmployeeAndAbsenceType]