SELECT [EmployeeID]
      ,[EmployeeNumber]
      ,[CountryID]
      ,[Code]
      ,[Name]
      ,[Firstname]
      ,[Lastname]
      ,[Birthday]
      ,[Street]
      ,[Housenumber]
      ,[Postalcode]
      ,[City]
      ,[Phonenumber]
      ,[Email]
  FROM [dbo].[EmployeesWithCountry]